[package]
name = "lando_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.32.3", features = ["android-native-activity", "persistence"] }
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
walkdir = "2.5.0"
rfd = "0.14.1"